### PR TITLE
BOP basic client for Worldmap

### PR DESCRIPTION
**Pull request by annarieger**
This PR introduces first steps for integration of the BOP heatmap layers into Harvard Worldmap application.

The corresponding issue can be found under https://github.com/terrestris/SolrHeatmap/issues/24.

Details:
- Text field based form `Twitter Heatmap`, where all `BOP Heatmap` layer parameter can be configured, was created and integrated as an additional tab into `Add Layers` dialog of the Worldmap application
  image
- Heatmap layer can be added to the global map and will be shown in the additional folder `BOP Heatmap Layers` in the layer tree. As layer name the configured parameter `q.keyword` will be taken.
  image
- Heatmap will be updated, if map extent will be changed (e.g. on zoom or move events)

Limitations:
- Heatmap cannot be persisted yet (it must be added every time on application load)

### CODE REVIEW

**Comment by capooti** [comment]
@ingenieroariel @bglewis what to do with this?

**Comment by ingenieroariel** [comment]
We will need to use most of that code, let's leave it open for now.

**Comment by capooti** [comment]
ok thanks

**Comment by capooti** [comment]
I am closing this for now.
We can re-open it at any time

**Pull request closed without merging**
