### PR TITLE
Gazetteer update

### PR DESCRIPTION
**Pull request by mbertrand**
- Added a username attribute to the GazetteerEntry model.  It will always be assigned to the layer's owner.

- Added a '/User/<username>' option to the Gazetter URL (so a sample URL would be http://worldmap.harvard.edu/Boston/User/mattbert

- If 'User/<username>' is in the URL then only features with that username will be returned.

- Fixed a bug: when layers were deleted, their gazetteer features were not deleted.  Now the gazetteer features should be deleted as well.

- Created an 'updategazetteer' management command ('python manage.py updategazetteer') that will assign usernames to any pre-existing gazetteer features that don't have usernames yet; and remove orphaned features of layers that no longer exist (see bug above).

- Anyone who can edit a layer's metadata can add the layer to the gazetteer and choose which fields are used for placenames and dates(if any).

- If a layer has start/end date metadata, and the user does not choose any particular layer attributes for the gazetteer start/end dates, then the metadata will be used to populate the gazetteer start/end dates.

- If a user chooses to add a layer to the gazetteer, a warning will be shown about how the layer's features will be searchable by anyone regardless of the layer permissions.

It was a little tricky getting things to run from a clean install, because the gazetteer uses GeoDjango 1.4 which doesn't play too well with PostGIS 2.0 - so I updated the README to show some PostGIS 2.0+ setup steps and added a SQL script, legacy_gist.sql, that runs during 'paver build' to make things more compatible.

### CODE REVIEW

**Comment by capooti** [comment]
thanks @mbertrand for the great work, and sorry for late feedback, I will discuss with @bglewis changes and push to production.

**Comment by capooti** [comment]
@mbertrand is anything required after merging?

**Comment by mbertrand** [comment]
No, nothing required.

**Comment by capooti** [comment]
Thanks @mbertrand, I am planning to merge it today and send it to production.
Not sure why there are migrations if there are no schema changes?

**Comment by mbertrand** [comment]
@capooti there is a new username field on the GazetteerEntry model

**Comment by capooti** [comment]
ok I will try this on my local instance and then deploy. Thanks @mbertrand

**Comment by capooti** [comment]
@mbertrand in my local instance I don't see the "gazetteer" menu item in GeoExplorer. Any idea why?

**Comment by capooti** [comment]
@mbertrand in my development instance I cannot see the "gazetteer" menu item in GXP. Any idea why this is happening? thanks

**Comment by capooti** [comment]
sorry, there was a defunct python process that was preventing new settings to take effect. thanks anyway

**Pull request merged**
